/**
 * AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Generated by `scripts/generate-model-map.js` from
 * `assets/models/model_registry.json` (source of truth).
 * Regenerated during Android build and via `npm run generate-model-map`.
 *
 * - MODEL_MAP: Metro static requires (bundle)
 * - MODEL_CATALOG: selection tree for getModelForUpscale (fast|sharp)
 *
 * Current: 35 fast (ESPCN) + 35 sharp (FSRCNN) = 70 models.
 */

/* eslint-disable @typescript-eslint/no-require-imports */

export type GeneratedUpscaleQuality = "fast" | "sharp";

/** Metro-bundled model assets keyed by filename. */
export const MODEL_MAP: Record<string, number> = {
  "espcn_128x_256x.tflite": require("../../assets/models/espcn_128x_256x.tflite"),
  "espcn_128x_384x.tflite": require("../../assets/models/espcn_128x_384x.tflite"),
  "espcn_128x_512x.tflite": require("../../assets/models/espcn_128x_512x.tflite"),
  "espcn_16x_128x.tflite": require("../../assets/models/espcn_16x_128x.tflite"),
  "espcn_16x_192x.tflite": require("../../assets/models/espcn_16x_192x.tflite"),
  "espcn_16x_256x.tflite": require("../../assets/models/espcn_16x_256x.tflite"),
  "espcn_16x_32x.tflite": require("../../assets/models/espcn_16x_32x.tflite"),
  "espcn_16x_384x.tflite": require("../../assets/models/espcn_16x_384x.tflite"),
  "espcn_16x_512x.tflite": require("../../assets/models/espcn_16x_512x.tflite"),
  "espcn_16x_64x.tflite": require("../../assets/models/espcn_16x_64x.tflite"),
  "espcn_192x_384x.tflite": require("../../assets/models/espcn_192x_384x.tflite"),
  "espcn_192x_576x.tflite": require("../../assets/models/espcn_192x_576x.tflite"),
  "espcn_256x_512x.tflite": require("../../assets/models/espcn_256x_512x.tflite"),
  "espcn_32x_128x.tflite": require("../../assets/models/espcn_32x_128x.tflite"),
  "espcn_32x_192x.tflite": require("../../assets/models/espcn_32x_192x.tflite"),
  "espcn_32x_256x.tflite": require("../../assets/models/espcn_32x_256x.tflite"),
  "espcn_32x_384x.tflite": require("../../assets/models/espcn_32x_384x.tflite"),
  "espcn_32x_512x.tflite": require("../../assets/models/espcn_32x_512x.tflite"),
  "espcn_32x_64x.tflite": require("../../assets/models/espcn_32x_64x.tflite"),
  "espcn_48x_144x.tflite": require("../../assets/models/espcn_48x_144x.tflite"),
  "espcn_48x_192x.tflite": require("../../assets/models/espcn_48x_192x.tflite"),
  "espcn_48x_240x.tflite": require("../../assets/models/espcn_48x_240x.tflite"),
  "espcn_48x_384x.tflite": require("../../assets/models/espcn_48x_384x.tflite"),
  "espcn_48x_576x.tflite": require("../../assets/models/espcn_48x_576x.tflite"),
  "espcn_48x_96x.tflite": require("../../assets/models/espcn_48x_96x.tflite"),
  "espcn_64x_128x.tflite": require("../../assets/models/espcn_64x_128x.tflite"),
  "espcn_64x_192x.tflite": require("../../assets/models/espcn_64x_192x.tflite"),
  "espcn_64x_256x.tflite": require("../../assets/models/espcn_64x_256x.tflite"),
  "espcn_64x_384x.tflite": require("../../assets/models/espcn_64x_384x.tflite"),
  "espcn_64x_512x.tflite": require("../../assets/models/espcn_64x_512x.tflite"),
  "espcn_96x_192x.tflite": require("../../assets/models/espcn_96x_192x.tflite"),
  "espcn_96x_288x.tflite": require("../../assets/models/espcn_96x_288x.tflite"),
  "espcn_96x_384x.tflite": require("../../assets/models/espcn_96x_384x.tflite"),
  "espcn_96x_480x.tflite": require("../../assets/models/espcn_96x_480x.tflite"),
  "espcn_96x_576x.tflite": require("../../assets/models/espcn_96x_576x.tflite"),
  "fsrcnn_128x_256x.tflite": require("../../assets/models/fsrcnn_128x_256x.tflite"),
  "fsrcnn_128x_384x.tflite": require("../../assets/models/fsrcnn_128x_384x.tflite"),
  "fsrcnn_128x_512x.tflite": require("../../assets/models/fsrcnn_128x_512x.tflite"),
  "fsrcnn_16x_128x.tflite": require("../../assets/models/fsrcnn_16x_128x.tflite"),
  "fsrcnn_16x_192x.tflite": require("../../assets/models/fsrcnn_16x_192x.tflite"),
  "fsrcnn_16x_256x.tflite": require("../../assets/models/fsrcnn_16x_256x.tflite"),
  "fsrcnn_16x_32x.tflite": require("../../assets/models/fsrcnn_16x_32x.tflite"),
  "fsrcnn_16x_384x.tflite": require("../../assets/models/fsrcnn_16x_384x.tflite"),
  "fsrcnn_16x_512x.tflite": require("../../assets/models/fsrcnn_16x_512x.tflite"),
  "fsrcnn_16x_64x.tflite": require("../../assets/models/fsrcnn_16x_64x.tflite"),
  "fsrcnn_192x_384x.tflite": require("../../assets/models/fsrcnn_192x_384x.tflite"),
  "fsrcnn_192x_576x.tflite": require("../../assets/models/fsrcnn_192x_576x.tflite"),
  "fsrcnn_256x_512x.tflite": require("../../assets/models/fsrcnn_256x_512x.tflite"),
  "fsrcnn_32x_128x.tflite": require("../../assets/models/fsrcnn_32x_128x.tflite"),
  "fsrcnn_32x_192x.tflite": require("../../assets/models/fsrcnn_32x_192x.tflite"),
  "fsrcnn_32x_256x.tflite": require("../../assets/models/fsrcnn_32x_256x.tflite"),
  "fsrcnn_32x_384x.tflite": require("../../assets/models/fsrcnn_32x_384x.tflite"),
  "fsrcnn_32x_512x.tflite": require("../../assets/models/fsrcnn_32x_512x.tflite"),
  "fsrcnn_32x_64x.tflite": require("../../assets/models/fsrcnn_32x_64x.tflite"),
  "fsrcnn_48x_144x.tflite": require("../../assets/models/fsrcnn_48x_144x.tflite"),
  "fsrcnn_48x_192x.tflite": require("../../assets/models/fsrcnn_48x_192x.tflite"),
  "fsrcnn_48x_240x.tflite": require("../../assets/models/fsrcnn_48x_240x.tflite"),
  "fsrcnn_48x_384x.tflite": require("../../assets/models/fsrcnn_48x_384x.tflite"),
  "fsrcnn_48x_576x.tflite": require("../../assets/models/fsrcnn_48x_576x.tflite"),
  "fsrcnn_48x_96x.tflite": require("../../assets/models/fsrcnn_48x_96x.tflite"),
  "fsrcnn_64x_128x.tflite": require("../../assets/models/fsrcnn_64x_128x.tflite"),
  "fsrcnn_64x_192x.tflite": require("../../assets/models/fsrcnn_64x_192x.tflite"),
  "fsrcnn_64x_256x.tflite": require("../../assets/models/fsrcnn_64x_256x.tflite"),
  "fsrcnn_64x_384x.tflite": require("../../assets/models/fsrcnn_64x_384x.tflite"),
  "fsrcnn_64x_512x.tflite": require("../../assets/models/fsrcnn_64x_512x.tflite"),
  "fsrcnn_96x_192x.tflite": require("../../assets/models/fsrcnn_96x_192x.tflite"),
  "fsrcnn_96x_288x.tflite": require("../../assets/models/fsrcnn_96x_288x.tflite"),
  "fsrcnn_96x_384x.tflite": require("../../assets/models/fsrcnn_96x_384x.tflite"),
  "fsrcnn_96x_480x.tflite": require("../../assets/models/fsrcnn_96x_480x.tflite"),
  "fsrcnn_96x_576x.tflite": require("../../assets/models/fsrcnn_96x_576x.tflite"),
};

/**
 * Selection catalog derived from the registry.
 * quality → input_size → scale → filename
 */
export const MODEL_CATALOG: Record<
  GeneratedUpscaleQuality,
  Record<number, Record<number, string>>
> = {
  fast: {
    16: {
      2: "espcn_16x_32x.tflite",
      4: "espcn_16x_64x.tflite",
      8: "espcn_16x_128x.tflite",
      12: "espcn_16x_192x.tflite",
      16: "espcn_16x_256x.tflite",
      24: "espcn_16x_384x.tflite",
      32: "espcn_16x_512x.tflite",
    },
    32: {
      2: "espcn_32x_64x.tflite",
      4: "espcn_32x_128x.tflite",
      6: "espcn_32x_192x.tflite",
      8: "espcn_32x_256x.tflite",
      12: "espcn_32x_384x.tflite",
      16: "espcn_32x_512x.tflite",
    },
    48: {
      2: "espcn_48x_96x.tflite",
      3: "espcn_48x_144x.tflite",
      4: "espcn_48x_192x.tflite",
      5: "espcn_48x_240x.tflite",
      8: "espcn_48x_384x.tflite",
      12: "espcn_48x_576x.tflite",
    },
    64: {
      2: "espcn_64x_128x.tflite",
      3: "espcn_64x_192x.tflite",
      4: "espcn_64x_256x.tflite",
      6: "espcn_64x_384x.tflite",
      8: "espcn_64x_512x.tflite",
    },
    96: {
      2: "espcn_96x_192x.tflite",
      3: "espcn_96x_288x.tflite",
      4: "espcn_96x_384x.tflite",
      5: "espcn_96x_480x.tflite",
      6: "espcn_96x_576x.tflite",
    },
    128: {
      2: "espcn_128x_256x.tflite",
      3: "espcn_128x_384x.tflite",
      4: "espcn_128x_512x.tflite",
    },
    192: {
      2: "espcn_192x_384x.tflite",
      3: "espcn_192x_576x.tflite",
    },
    256: {
      2: "espcn_256x_512x.tflite",
    },
  },
  sharp: {
    16: {
      2: "fsrcnn_16x_32x.tflite",
      4: "fsrcnn_16x_64x.tflite",
      8: "fsrcnn_16x_128x.tflite",
      12: "fsrcnn_16x_192x.tflite",
      16: "fsrcnn_16x_256x.tflite",
      24: "fsrcnn_16x_384x.tflite",
      32: "fsrcnn_16x_512x.tflite",
    },
    32: {
      2: "fsrcnn_32x_64x.tflite",
      4: "fsrcnn_32x_128x.tflite",
      6: "fsrcnn_32x_192x.tflite",
      8: "fsrcnn_32x_256x.tflite",
      12: "fsrcnn_32x_384x.tflite",
      16: "fsrcnn_32x_512x.tflite",
    },
    48: {
      2: "fsrcnn_48x_96x.tflite",
      3: "fsrcnn_48x_144x.tflite",
      4: "fsrcnn_48x_192x.tflite",
      5: "fsrcnn_48x_240x.tflite",
      8: "fsrcnn_48x_384x.tflite",
      12: "fsrcnn_48x_576x.tflite",
    },
    64: {
      2: "fsrcnn_64x_128x.tflite",
      3: "fsrcnn_64x_192x.tflite",
      4: "fsrcnn_64x_256x.tflite",
      6: "fsrcnn_64x_384x.tflite",
      8: "fsrcnn_64x_512x.tflite",
    },
    96: {
      2: "fsrcnn_96x_192x.tflite",
      3: "fsrcnn_96x_288x.tflite",
      4: "fsrcnn_96x_384x.tflite",
      5: "fsrcnn_96x_480x.tflite",
      6: "fsrcnn_96x_576x.tflite",
    },
    128: {
      2: "fsrcnn_128x_256x.tflite",
      3: "fsrcnn_128x_384x.tflite",
      4: "fsrcnn_128x_512x.tflite",
    },
    192: {
      2: "fsrcnn_192x_384x.tflite",
      3: "fsrcnn_192x_576x.tflite",
    },
    256: {
      2: "fsrcnn_256x_512x.tflite",
    },
  },
};

/** Filenames present in MODEL_MAP. */
export const AVAILABLE_MODEL_FILES: ReadonlySet<string> = new Set(
  Object.keys(MODEL_MAP),
);
