/**
 * AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Generated by `scripts/generate-model-map.js` from the `*.tflite` files that
 * physically exist in `assets/models/`. It is regenerated automatically during
 * the build (see `scripts/build-android.sh`) and via `npm run generate-model-map`.
 *
 * Because the require list is derived from a directory scan, it can never
 * reference a missing file: the build never fails on absent models, and newly
 * generated models are bundled automatically on the next build.
 *
 * Current contents: 0 fast (ESPCN) + 4 sharp (FSRCNN) = 4 models.
 */

/* eslint-disable @typescript-eslint/no-require-imports */
// Metro resolves these static `require` paths at build time.
export const MODEL_MAP: Record<string, number> = {
  "fsrcnn_16x_128x.tflite": require("../../assets/models/fsrcnn_16x_128x.tflite"),
  "fsrcnn_16x_192x.tflite": require("../../assets/models/fsrcnn_16x_192x.tflite"),
  "fsrcnn_16x_256x.tflite": require("../../assets/models/fsrcnn_16x_256x.tflite"),
  "fsrcnn_16x_64x.tflite": require("../../assets/models/fsrcnn_16x_64x.tflite"),
};

/** The set of model file names that are actually bundled. */
export const AVAILABLE_MODEL_FILES: ReadonlySet<string> = new Set(
  Object.keys(MODEL_MAP),
);
