/**
 * Edge-AI icon processing for the picker.
 *
 * - `upscaleIconAi` uses react-native-fast-tflite with multiple bundled super-resolution
 *   models (ESPCN/LapSRN style). Model is selected dynamically based on input size
 *   and target output size (determined by device pixel density).
 * - If the native module or model is unavailable, it transparently falls back to
 *   the existing bilinear `upscaleIconIfSmall` so the button always works.
 * - `isLowResIcon` detects icons small enough to benefit from upscaling.
 * - White-background removal is handled by whiteBgRemoval.ts using
 *   expo-image-manipulator + upng-js (no WebView needed).
 */

import { Dimensions, Image, PixelRatio } from "react-native";
import { mimeForFormat, upscaleIconIfSmall } from "./iconUpscaler";

// Below this max dimension an icon is "low-res" and worth upscaling.
const LOW_RES_THRESHOLD_PX = 64;

// Base display size for icons (what we want to show on screen)
const BASE_DISPLAY_SIZE = 64;

// Model registry - maps input_size -> { scale -> model_file }
// Generated by train_espcn_multi.py
const MODEL_REGISTRY: Record<number, Record<number, string>> = {
  16: {
    4: "espcn_16x_64x.tflite",
    8: "espcn_16x_128x.tflite",
    12: "espcn_16x_192x.tflite",
    16: "espcn_16x_256x.tflite",
    24: "espcn_16x_384x.tflite",
    32: "espcn_16x_512x.tflite",
  },
  32: {
    2: "espcn_32x_64x.tflite",
    4: "espcn_32x_128x.tflite",
    6: "espcn_32x_192x.tflite",
    8: "espcn_32x_256x.tflite",
    12: "espcn_32x_384x.tflite",
    16: "espcn_32x_512x.tflite",
  },
  48: {
    2: "espcn_48x_96x.tflite",
    3: "espcn_48x_144x.tflite",
    4: "espcn_48x_192x.tflite",
    5: "espcn_48x_240x.tflite",
    8: "espcn_48x_384x.tflite",
    12: "espcn_48x_576x.tflite",
  },
  64: {
    2: "espcn_64x_128x.tflite",
    3: "espcn_64x_192x.tflite",
    4: "espcn_64x_256x.tflite",
    6: "espcn_64x_384x.tflite",
    8: "espcn_64x_512x.tflite",
  },
};

// Static model map - Metro requires static paths at build time
const MODEL_MAP: Record<string, any> = {
  "espcn_16x_64x.tflite": require("../../assets/models/espcn_16x_64x.tflite"),
  "espcn_16x_128x.tflite": require("../../assets/models/espcn_16x_128x.tflite"),
  "espcn_16x_192x.tflite": require("../../assets/models/espcn_16x_192x.tflite"),
  "espcn_16x_256x.tflite": require("../../assets/models/espcn_16x_256x.tflite"),
  "espcn_16x_384x.tflite": require("../../assets/models/espcn_16x_384x.tflite"),
  "espcn_16x_512x.tflite": require("../../assets/models/espcn_16x_512x.tflite"),
  "espcn_32x_64x.tflite": require("../../assets/models/espcn_32x_64x.tflite"),
  "espcn_32x_128x.tflite": require("../../assets/models/espcn_32x_128x.tflite"),
  "espcn_32x_192x.tflite": require("../../assets/models/espcn_32x_192x.tflite"),
  "espcn_32x_256x.tflite": require("../../assets/models/espcn_32x_256x.tflite"),
  "espcn_32x_384x.tflite": require("../../assets/models/espcn_32x_384x.tflite"),
  "espcn_32x_512x.tflite": require("../../assets/models/espcn_32x_512x.tflite"),
  "espcn_48x_96x.tflite": require("../../assets/models/espcn_48x_96x.tflite"),
  "espcn_48x_144x.tflite": require("../../assets/models/espcn_48x_144x.tflite"),
  "espcn_48x_192x.tflite": require("../../assets/models/espcn_48x_192x.tflite"),
  "espcn_48x_240x.tflite": require("../../assets/models/espcn_48x_240x.tflite"),
  "espcn_48x_384x.tflite": require("../../assets/models/espcn_48x_384x.tflite"),
  "espcn_48x_576x.tflite": require("../../assets/models/espcn_48x_576x.tflite"),
  "espcn_64x_128x.tflite": require("../../assets/models/espcn_64x_128x.tflite"),
  "espcn_64x_192x.tflite": require("../../assets/models/espcn_64x_192x.tflite"),
  "espcn_64x_256x.tflite": require("../../assets/models/espcn_64x_256x.tflite"),
  "espcn_64x_384x.tflite": require("../../assets/models/espcn_64x_384x.tflite"),
  "espcn_64x_512x.tflite": require("../../assets/models/espcn_64x_512x.tflite"),
};

// Cache for loaded models
const loadedModels: Map<string, any> = new Map();
let modelsLoaded = false;
let modelLoadFailed = false;

/**
 * Get the target output size based on device pixel density.
 * Returns the size needed to appear crisp on the current device.
 */
export function getTargetOutputSize(): number {
  const pixelRatio = PixelRatio.get();
  const { width: screenWidth } = Dimensions.get("window");

  // For icons displayed at BASE_DISPLAY_SIZE pixels, we need to account for pixel density
  // On high-DPI screens (pixelRatio > 1), we need larger images
  const targetSize = Math.round(BASE_DISPLAY_SIZE * pixelRatio);

  // Clamp to reasonable bounds
  return Math.min(Math.max(targetSize, 64), 512);
}

/**
 * Find the nearest input size in our model registry.
 */
function findNearestInputSize(actualSize: number): number {
  const sizes = Object.keys(MODEL_REGISTRY)
    .map(Number)
    .sort((a, b) => a - b);

  // Exact match
  if (sizes.includes(actualSize)) return actualSize;

  // Find nearest smaller size
  const candidates = sizes.filter((s) => s <= actualSize);
  if (candidates.length > 0) return Math.max(...candidates);

  // If icon is smaller than all supported, use smallest input size
  return sizes[0];
}

/**
 * Find the best scale factor for achieving target output from input.
 */
function findBestScale(inputSize: number, targetOutput: number): number | null {
  const scaleMap = MODEL_REGISTRY[inputSize];
  if (!scaleMap) return null;

  // Find scales that get us closest to target
  const scales = Object.keys(scaleMap)
    .map(Number)
    .sort((a, b) => a - b);

  // Exact match first
  const exactScale = targetOutput / inputSize;
  if (scales.includes(exactScale)) return exactScale;

  // Find scale that minimizes difference
  let bestScale = scales[0];
  let minDiff = Math.abs(targetOutput - inputSize * bestScale);

  for (const scale of scales) {
    const output = inputSize * scale;
    const diff = Math.abs(targetOutput - output);
    if (diff < minDiff) {
      minDiff = diff;
      bestScale = scale;
    }
  }

  return bestScale;
}

/**
 * Get model info for a given input size and target output.
 * Returns { inputSize, scale, modelFile, outputSize } or null if no match.
 */
export function getModelForUpscale(
  inputSize: number,
  targetOutput: number,
): {
  inputSize: number;
  scale: number;
  modelFile: string;
  outputSize: number;
} | null {
  const nearestInput = findNearestInputSize(inputSize);
  const scale = findBestScale(nearestInput, targetOutput);

  if (scale === null) return null;

  const modelFile = MODEL_REGISTRY[nearestInput][scale];
  if (!modelFile) return null;

  return {
    inputSize: nearestInput,
    scale,
    modelFile,
    outputSize: nearestInput * scale,
  };
}

/**
 * Check if the Tflite native module is available by probing NativeModules
 * before attempting any import/require. The package's top-level code calls
 * TurboModuleRegistry.getEnforcing(...) which crashes if the native module
 * isn't linked (e.g. Expo Go), so we must avoid loading the JS module at all.
 */
function tfliteModuleExists(): boolean {
  try {
    const TurboModuleRegistry = require("react-native").TurboModuleRegistry;
    // react-native-fast-tflite exposes its TurboModule under the name "Tflite".
    const mod =
      TurboModuleRegistry &&
      (TurboModuleRegistry.get
        ? TurboModuleRegistry.get("Tflite")
        : TurboModuleRegistry.getEnforcing("Tflite"));
    return !!mod;
  } catch {
    return false;
  }
}

/**
 * Load a specific model by file name.
 */
async function loadModel(modelFile: string): Promise<any | null> {
  if (modelLoadFailed) return null;

  // Return cached model if available
  if (loadedModels.has(modelFile)) {
    return loadedModels.get(modelFile);
  }

  if (!tfliteModuleExists()) {
    modelLoadFailed = true;
    console.warn("[ICON_AI] RNTflite native module not available");
    return null;
  }

  try {
    const { loadTensorflowModel } = require("react-native-fast-tflite");
    if (!loadTensorflowModel) return null;

    const modelAsset = MODEL_MAP[modelFile];
    if (!modelAsset) {
      console.warn(`[ICON_AI] Model not found in map: ${modelFile}`);
      return null;
    }

    const model = await loadTensorflowModel(modelAsset);
    console.log(`[ICON_AI] Loaded model: ${modelFile}`);
    loadedModels.set(modelFile, model);
    return model;
  } catch (err) {
    modelLoadFailed = true;
    console.warn(`[ICON_AI] Failed to load model ${modelFile}:`, err);
    return null;
  }
}

export function isLowResIcon(
  base64: string,
  format: string,
  originalWidth?: number,
  originalHeight?: number,
): Promise<boolean> {
  return new Promise((resolve) => {
    if (format === "svg") {
      resolve(false);
      return;
    }
    // If we have original dimensions stored (from before upscaling), use those
    // directly -- no need to decode the image again. This is the key fix for the
    // "Upscale" button not appearing: icons are upscaled to 256px before storage,
    // so the current imageData always looks "large enough".
    if (originalWidth !== undefined && originalHeight !== undefined) {
      resolve(Math.max(originalWidth, originalHeight) < LOW_RES_THRESHOLD_PX);
      return;
    }
    const mime = mimeForFormat(format);
    const uri = `data:${mime};base64,${base64}`;
    Image.getSize(
      uri,
      (w: number, h: number) => {
        resolve(Math.max(w, h) < LOW_RES_THRESHOLD_PX);
      },
      () => resolve(false),
    );
  });
}

/**
 * Upscale a small raster icon using the edge-AI model when available, else the
 * bilinear fallback. Always returns a base64 plus the output format.
 *
 * `force` skips the "already large enough" short-circuit so an explicit user
 * tap always produces a crisper, larger icon (the stored bytes may already be
 * a 256px bilinear upscale from crawl time, which is still low quality).
 *
 * The target output size is determined dynamically based on device pixel density.
 */
export async function upscaleIconAi(
  base64: string,
  format: string,
  force = false,
): Promise<{ base64: string; format: string }> {
  if (format === "svg") return { base64, format };

  // Get actual input dimensions
  const mime = mimeForFormat(format);
  const srcUri = `data:${mime};base64,${base64}`;

  const inputSize = await new Promise<number>((resolve, reject) => {
    Image.getSize(
      srcUri,
      (w, h) => resolve(Math.max(w, h)),
      (err) => reject(err),
    );
  }).catch(() => 32); // Default fallback

  // Get target output based on device pixel density
  const targetOutput = getTargetOutputSize();

  console.log(`[ICON_AI] Upscaling ${inputSize}px → target ${targetOutput}px`);

  // Find appropriate model
  const modelInfo = getModelForUpscale(inputSize, targetOutput);

  if (!modelInfo) {
    console.log(
      `[ICON_AI] No model found for ${inputSize}→${targetOutput}, using bilinear`,
    );
    return upscaleIconIfSmall(base64, format, force);
  }

  const model = await loadModel(modelInfo.modelFile);
  if (!model) {
    return upscaleIconIfSmall(base64, format, force);
  }

  try {
    const { manipulateAsync, SaveFormat } =
      await import("expo-image-manipulator");
    const { readAsStringAsync, EncodingType } =
      await import("expo-file-system/legacy");
    const { deleteAsync } = await import("expo-file-system/legacy");
    const UPNG = (await import("upng-js")).default;

    // Resize to the model's expected input size
    const bounded = await manipulateAsync(
      srcUri,
      [{ resize: { width: modelInfo.inputSize, height: modelInfo.inputSize } }],
      { compress: 1, format: SaveFormat.PNG },
    );

    // Read the resized PNG and decode to get RGB pixels for the model.
    const inputB64 = await readAsStringAsync(bounded.uri, {
      encoding: EncodingType.Base64,
    });

    // Decode PNG to get raw RGBA pixels.
    const decoded = UPNG.decode(
      Uint8Array.from(atob(inputB64), (c) => c.charCodeAt(0)).buffer,
    ) as any;
    const rgbaIn = new Uint8ClampedArray(
      decoded.data as unknown as ArrayBuffer,
    );

    // Extract RGB planes (model expects 3 channels, no alpha).
    const rgbIn = new Float32Array(
      modelInfo.inputSize * modelInfo.inputSize * 3,
    );
    let srcP = 0;
    for (let i = 0; i < modelInfo.inputSize * modelInfo.inputSize; i++) {
      rgbIn[i * 3] = rgbaIn[srcP++] / 255;
      rgbIn[i * 3 + 1] = rgbaIn[srcP++] / 255;
      rgbIn[i * 3 + 2] = rgbaIn[srcP++] / 255;
      srcP++; // skip alpha
    }

    // Run ESPCN with the selected model
    const out: Float32Array[] = await model.runSync([rgbIn]);
    const outBytes = out[0];
    const outW = modelInfo.outputSize;
    const outH = modelInfo.outputSize;

    // Allocate RGBA buffer for upng-js (expects 4 channels).
    // Model outputs float32 0-1, convert to uint8 0-255.
    const rgba = new Uint8Array(outW * outH * 4);
    let p = 0;
    for (let i = 0; i < outW * outH; i++) {
      rgba[i * 4] = Math.round(outBytes[p++] * 255);
      rgba[i * 4 + 1] = Math.round(outBytes[p++] * 255);
      rgba[i * 4 + 2] = Math.round(outBytes[p++] * 255);
      rgba[i * 4 + 3] = 255;
    }

    // Encode the upscaled RGBA back to a PNG
    const pngData = UPNG.encode([rgba.buffer as ArrayBuffer], outW, outH, 0);
    const uint8 = new Uint8Array(pngData);
    let outB64 = "";
    const chunkSize = 8192;
    for (let i = 0; i < uint8.length; i += chunkSize) {
      const end = Math.min(i + chunkSize, uint8.length);
      outB64 += String.fromCharCode(...uint8.subarray(i, end));
    }
    const result = btoa(outB64);

    await deleteAsync(bounded.uri, { idempotent: true }).catch(() => {});
    console.log(
      `[ICON_AI] Upscaled ${inputSize}px → ${outW}x${outH}px using ${modelInfo.modelFile}`,
    );
    return { base64: result, format: "png" };
  } catch (err) {
    console.warn("[ICON_AI] model run failed, bilinear fallback:", err);
    return upscaleIconIfSmall(base64, format, true);
  }
}
